# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Adventures in Swift
tagline:          Unit Testing and Clean Code Exploration
url:              https://mr-v.github.io
paginate:         1
baseurl:          /
author:
  name:           Witold Skibniewski
  url:            https://github.com/mr-v
  email:          witold.skibniewski@gmail.com

# Custom vars
version:          0.0.1
github:
  repo:           https://github.com/mr-v/mr-v.github.io
pages_list:
  About: '/about'
  Feed: '/atom.xml'
#  Archive: '/archive'

# turn on recognition of github flavored markdown
markdown: redcarpet

excerpt_separator: <!--more-->
